# Generated by Django 2.1 on 2019-01-12 08:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20190112_0623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='friend', to=settings.AUTH_USER_MODEL, verbose_name='Друзья'),
        ),
    ]
